version: '3.8'

services:
  llama-server:
    build: .
    container_name: gemma_server
    ports:
      - "8080:8080"
    environment:
      - HF_TOKEN=${HF_TOKEN}
    volumes:
      # Mount thư mục ./models_cache vào /models trong container để cache lại file đã tải, 
      # không phải tải lại model nếu bạn khởi động lại container.
      - ./models_cache:/models
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    restart: unless-stopped
